### ISSUE TITLE
Moonlight-Desktop Prototype

### ISSUE THREAD

**Issue by microchipmatt** [Jorys-Paulin/moonlight-desktop-prototype#1]
Okay, I have it running, I see hello world etc, and resolution.  So how do I:

-Connect to a gamestream server
- are there any command lines I can use to specify game to load etc

**Comment by Jorys-Paulin** [comment]
@microchipmatt As I said, it's a prototype which only captures the selected screen at a select resolution. This project is meant to replace GFE, however, they are some problems, like:
- How to launch your games?
- How to emulate mouse, keyboard and gamepad?

**Comment by Jorys-Paulin** [comment]
@microchipmatt This prototype is now abandoned, as I'm working on a new version over at https://github.com/Jorys-Paulin/moonlight-desktop, which is a better version still in active development. Also, note that there's a better version of Moonlight coming: https://github.com/moonlight-stream/moonlight-qt
